<a href="https://colab.research.google.com/github/chetankhairnar05/Python_Automation/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# First, you must install the required Python library.
# You also need to have Java installed on your system for tabula-py to work, as it's a wrapper for the Tabula-Java library.
# You can run this command in your terminal or a Colab cell:
!pip install tabula-py pandas

import pandas as pd
import tabula

# Define the URL to a sample PDF file with tables.
# This URL points to a public PDF document that is known to work with tabula.
pdf_url = "https://assets.accessible-digital-documents.com/uploads/2017/01/sample-tables.pdf"
output_filename = "extracted_tables.xlsx"

# --- Step 1: Read the tables from the PDF ---
# tabula.read_pdf returns a list of DataFrames, one for each table it finds.
# The 'multiple_tables=True' parameter tells tabula to look for multiple tables per page.
# The 'pages="all"' parameter tells tabula to process all pages in the PDF.
print(f"Extracting tables from PDF: {pdf_url}")
try:
    dfs = tabula.read_pdf(pdf_url, pages="all", multiple_tables=True, stream=True)
    print(f"Successfully extracted {len(dfs)} tables.")
except Exception as e:
    print(f"Error extracting tables from the PDF: {e}")
    # An empty list is fine if no tables are found, but a more specific error is useful
    dfs = []

# --- Step 2: Process and Display the extracted DataFrames ---
if len(dfs) > 0:
    for i, df in enumerate(dfs):
        print(f"\n--- Table {i + 1} from the PDF ---")
        print(df.head()) # Print the first 5 rows of each extracted table

# --- Step 3: (Optional) Export all tables to a single Excel file on separate sheets ---
if len(dfs) > 0:
    try:
        with pd.ExcelWriter(output_filename, engine='xlsxwriter') as writer:
            for i, df in enumerate(dfs):
                sheet_name = f"Table_{i + 1}"
                # Handle potential MultiIndex columns
                if isinstance(df.columns, pd.MultiIndex):
                    df.columns = ['_'.join(col).strip() if isinstance(col, tuple) else str(col) for col in df.columns.values]
                    df.columns = [col.replace('nan_', '').replace('_nan', '') for col in df.columns]

                df.to_excel(writer, sheet_name=sheet_name, index=False)
        print(f"\nSuccessfully exported all tables to '{output_filename}'.")
    except Exception as e:
        print(f"\nError exporting tables to Excel: {e}")

# --- Step 4: (Optional) Download the Excel file in a Colab environment ---
# This part is only for use in Google Colab. If you're running locally, you don't need this.
try:
    from google.colab import files
    print("Downloading the Excel file to your local machine.")
    files.download(output_filename)
except ImportError:
    print("\nNote: 'google.colab' module not found. This download step is skipped.")

Collecting tabula-py
  Downloading tabula_py-2.10.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.11/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading tabula_py-2.10.0-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 89.9 MB/s eta 0:00:00
Installing collected packages: tabula-py
Successfully installed tabula-py-2.10.0
Extracting tables from PDF: https://assets.accessible-digital-documents.com/uploads/2017/01/sample-tables.pdf

WARNING:tabula.backend:Failed to import jpype dependencies. Fallback to subprocess.
WARNING:tabula.backend:No module named 'jpype'
WARNING:tabula.backend:Got stderr: Aug 07, 2025 10:44:11 AM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
WARNING: New fonts found, font cache will be re-built
Aug 07, 2025 10:44:12 AM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Building on-disk font cache, this may take a while
Aug 07, 2025 10:44:12 AM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Finished building on-disk font cache, found 17 fonts
Aug 07, 2025 10:44:12 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'Verdana'
Aug 07, 2025 10:44:12 AM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font Symbol
Aug 07, 2025 10:44:12 AM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font ZapfDingbats
Aug 07, 2025 10:44:12 AM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for Times_Roman
Aug 07, 2025 10:44:12 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSerif-Bold' for 'TimesNewRomanPS-BoldMT'
Aug 07, 2025 10:44:14 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'Verdana'
Aug 07, 2025 10:44:14 AM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for Times_Roman
Aug 07, 2025 10:44:14 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSerif-Bold' for 'TimesNewRomanPS-BoldMT'
Aug 07, 2025 10:44:14 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans-Bold' for 'TrebuchetMS-Bold'
Aug 07, 2025 10:44:15 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'Verdana'
Aug 07, 2025 10:44:15 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans-Bold' for 'TrebuchetMS-Bold'
Aug 07, 2025 10:44:16 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'Verdana'
Aug 07, 2025 10:44:16 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSerif-Bold' for 'Georgia-Bold'
Aug 07, 2025 10:44:16 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'Verdana'
Aug 07, 2025 10:44:16 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSerif-Bold' for 'Georgia-Bold'
Aug 07, 2025 10:44:17 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'Verdana'
Aug 07, 2025 10:44:17 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'Verdana'
Aug 07, 2025 10:44:17 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSerif-Bold' for 'Georgia-Bold'
Aug 07, 2025 10:44:17 AM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for Times_Roman
Aug 07, 2025 10:44:18 AM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for Times_Roman
Aug 07, 2025 10:44:18 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'Verdana'
Aug 07, 2025 10:44:18 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSerif-Bold' for 'TimesNewRomanPS-BoldMT'
Aug 07, 2025 10:44:18 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'Verdana'
Aug 07, 2025 10:44:19 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'Verdana'
Aug 07, 2025 10:44:19 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'Verdana'
Aug 07, 2025 10:44:19 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'Verdana'

Successfully extracted 29 tables.

--- Table 1 from the PDF ---
  Column header (TH) Column header (TH).1 Column header (TH).2
0    Row header (TH)       Data cell (TD)       Data cell (TD)
1     Row header(TH)       Data cell (TD)       Data cell (TD)

--- Table 2 from the PDF ---
         Expenditure by function £ million  2009/10  2010/11 1
0               Policy functions Financial    22.50      30.57
1                            Information 2    10.20      14.80
2                              Contingency     2.60       1.20
3  Remunerated functions Agency services 3    44.70      35.91
4                                 Payments    22.41      19.88

--- Table 3 from the PDF ---
  Main character Daniel Radcliffe
0     Sidekick 1     Rupert Grint
1     Sidekick 2      Emma Watson
2   Lovable ogre  Robbie Coltrane
3      Professor     Maggie Smith
4     Headmaster   Richard Harris

--- Table 4 from the PDF ---
             Role             Actor
0  Main character  Daniel Radcliffe
1      Sidekick 1      Rupert Grint
2      Sidekick 2       Emma Watson
3    Lovable ogre   Robbie Coltrane
4       Professor      Maggie Smith

--- Table 5 from the PDF ---
           Unnamed: 0   2010   2009   2008
0  Non-current assets    NaN    NaN    NaN
1            Property  345.0  445.0  222.0
2          Investment  567.0  654.0  423.0
3         Intangibles  423.0  123.0  453.0
4      Current assets    NaN    NaN    NaN

--- Table 6 from the PDF ---
       Rainfall  Americas    Asia  Europe  Africa
0      (inches)       NaN     NaN     NaN     NaN
1           NaN       NaN  2010.0     NaN     NaN
2       Average     104.0   201.0   193.0   144.0
3  24 hour high      15.0    26.0    27.0    18.0
4  12 hour high       9.0    10.0    11.0    12.0

--- Table 7 from the PDF ---
  Non-current assets  2010  2009  2008
0           Property   345   445   222
1         Investment   567   654   423
2        Intangibles   423   123   453

--- Table 8 from the PDF ---
                Current assets  2010  2009  2008
0  Trade and other receivables   435   634   231
1    Cash and cash equivalents   524   123   482
2                        Other   223   211   254

--- Table 9 from the PDF ---
  Rainfall (inches)  Americas  Asia  Europe  Africa
0           Average       133   244     155     166
1      24 hour high        27    28      29      20
2      12 hour high        11    12      13      16

--- Table 10 from the PDF ---
               Unnamed: 0 2011 Unnamed: 1 2010 restated
0                     NaN  NaN        NaN           NaN
1          General income  NaN    250,000       200,000
2  Increase in value, WIP  NaN     15,000        30,000
3                     NaN  NaN    265,000       230,000
4    Administrative costs  NaN        NaN           NaN

--- Table 11 from the PDF ---
             Unnamed: 0         Unnamed: 1       2011 2010 restated
0                Income     General income    250,000       200,000
1                   NaN  Increase in value     15,000        30,000
2                   NaN       Total income    265,000       230,000
3  Administrative costs        Staff costs  (200,000)     (150,000)
4                   NaN   Early departures   (10,000)      (20,000)

--- Table 12 from the PDF ---
  Unnamed: 0                         Unnamed: 1 2008  Unnamed: 2  \
0       Name                                Yes   No         NaN
1        Bob                                  2    5         NaN
2        Sue                                  3    8         NaN
3        Sam  [data relating to both columns in  NaN         NaN
4        NaN       a single cell spanning both]  NaN         NaN

                          Unnamed: 3 2009
0                                Yes   No
1                                  6    7
2                                  4    7
3  [data relating to both columns in  NaN
4       a single cell spanning both]  NaN

--- Table 13 from the PDF ---
                         Question Respondent A Respondent B Respondent C
0           Are you a UK citizen?                                    
1     Are you currently employed?                                    
2  Do you have a driving licence?                                    

--- Table 14 from the PDF ---
                         Question Respondent A Respondent B Respondent C
0           Are you a UK citizen?           No          Yes           No
1     Are you currently employed?          Yes           No          Yes
2  Do you have a driving licence?           No           No          Yes

--- Table 15 from the PDF ---
                Unnamed: 0  2006  2007  2008  2009
0                Economics  A, B  A, C  A, B  A, C
1  International relations  A, E  A, E  A, B  A, E
2               Philosophy     A     A     A  A, D
3                 Politics  A, D  A, D  A, D     A
4              Mathematics  B, C     B  A, E  A, B

--- Table 16 from the PDF ---
                Unnamed: 0 2006 2007 2008 2009
0                Economics   No  Yes  Yes  Yes
1  International relations   No   No   No   No
2               Philosophy   No   No   No   No
3                 Politics   No   No   No   No
4              Mathematics  Yes   No   No   No

--- Table 17 from the PDF ---
        Accounting item  Unnamed: 0              Unnamed: 1     2011
0                Income         NaN          General income  200,000
1                   NaN         NaN  Increase in value, WIP   30,000
2                   NaN         NaN         Income subtotal  230,000
3  Administrative costs         NaN                   Staff  150,000
4                   NaN         NaN        Early departures   20,000

--- Table 18 from the PDF ---
        Accounting item  Unnamed: 0              Unnamed: 1       2011
0                Income         NaN          General income    200,000
1                   NaN         NaN  Increase in value, WIP     30,000
2                   NaN         NaN         Income subtotal    230,000
3  Administrative costs         NaN                   Staff  (150,000)
4                   NaN         NaN        Early departures   (20,000)

--- Table 19 from the PDF ---
       Country  1980  1990  2000   2010
0  Afghanistan  0.78  1.48  2.16   3.33
1      Albania  8.89  9.67  9.89  10.38
2      Algeria  4.74  3.33  5.50   7.24
3      Andorra  4.98  5.63  9.09  10.35
4       Angola     -     -  4.42   4.42

--- Table 20 from the PDF ---
          Expenditure by function £million  2009/10  2010/11 1
0               Policy functions Financial    22.50      30.57
1                            Information 2    10.20      14.80
2                              Contingency     2.60       1.20
3  Remunerated functions Agency services 3    44.70      35.91
4                                 Payments    22.41      19.88

--- Table 21 from the PDF ---
        Expenditure by function £million  2009/10  2010/11
0             Policy functions Financial    22.50    30.57
1                            Information    10.20    14.80
2                            Contingency     2.60     1.20
3  Remunerated functions Agency services    44.70    35.91
4                               Payments    22.41    19.88

--- Table 22 from the PDF ---
     Expenditure £m                         Notes   2010   2011
0               NaN  (Notes located on  page [n])    NaN    NaN
1       Information                             1  10.20  14.80
2       Contingency                           NaN   2.60   1.20
3          Payments                             3  22.41  19.88
4  Banking services                             4  22.90  44.23

--- Table 23 from the PDF ---
  Unnamed: 0 Unnamed: 1       2008 Unnamed: 2       2009
0        NaN        NaN        NaN        NaN        NaN
1       Name    Entered  Completed    Entered  Completed
2        Bob         22         21         20         19
3        Sue         44         12         12         10

--- Table 24 from the PDF ---
           Unnamed: 0   2010   2009   2008
0  Non-current assets    NaN    NaN    NaN
1           Buildings  345.0  445.0  222.0
2          Investment  567.0  654.0  423.0
3         Intangibles  423.0  123.0  453.0
4      Current assets    NaN    NaN    NaN

--- Table 25 from the PDF ---
  Unnamed: 0 Unnamed: 1  2008 Unnamed: 2 Unnamed: 3  2009 Unnamed: 4
0       Name    Entered   NaN        Won    Entered   NaN        Won
1        Bob         22   NaN         21         20   NaN         19
2        Sue         44   NaN         12         12   NaN         10
3        Sam         16   NaN          4         45   NaN         30

--- Table 26 from the PDF ---
                Unnamed: 0  2006  2007  2008  2009
0                Economics  A, B  A, C  A, C  A, C
1  International relations  A, E  A, E  A, B  A, B
2               Philosophy     A     A     A     A
3                 Politics  A, D  A, D  A, B     A
4              Mathematics  B, C     B  A, B  A, B

--- Table 27 from the PDF ---
                                   Name  Apples  Pears
0                             Bob Scott      20     25
1  Susan. P. Arnold-Jones, BA, FRSA, MD      24     15
2                  Sam Holder-Dickinson      14     10

--- Table 28 from the PDF ---
           Unnamed: 0   2010   2009   2008
0  Non-current assets    NaN    NaN    NaN
1           Buildings  345.0  445.0  222.0
2          Investment  567.0  654.0  423.0
3         Intangibles  423.0  123.0  453.0
4      Current assets    NaN    NaN    NaN

--- Table 29 from the PDF ---
            Unnamed: 0 South America   Asia  Africa  Australia
0                  NaN          2010    NaN     NaN        NaN
1      Highest average         523.6  467.4   405.0      340.5
2  Highest in 24 hours          73.1   54.1    27.2       66.3
3  Highest in 12 hours         42 .4   30.1    15.9       40.3
4                  NaN          2009    NaN     NaN        NaN

Error exporting tables to Excel: No module named 'xlsxwriter'
Downloading the Excel file to your local machine.

FileNotFoundError: Cannot find file: extracted_tables.xlsx